## Revisions & Notes {-}

**General Notes**

1. The following CoCs are retained in dataframe but only have 5 years of data (missing 1 yearly observation): AR-505, FL-500, MD-500, MD-507, MD-508, MD-510, MD-512, NC-509, NY-501

2. The following CoCs are removed from dataframe due to lacking 2 or more yearly observations: CA-523, CA-529, CA-530, CA-531, CO-505, MP-500, NJ-512, NY-525, OR-504 


**Revisions to the Historic Housing Inventory Counts**

On one occasion, the Housing Inventory Counts published in prior editions of the AHAR was subsequently updated. The figures described in this file represent the latest versions of these data (as of the publication of this file). The sole revision is summarized below:

1. Beginning in the 2016 AHAR Part 1, the number of year-round PSH beds for households with only children was lowered by 539 beds in the Riverside City & County CoC, CA-608.

2. a MO-604 covers territory in both Missouri and Kansas. The record described in this file represents the CoC's total territory, the sum of the housing inventory counts the CoC separately reported for the portions of its territory in MO and in KS. However, in the companion file, Housing Inventory Count by State, MO-604's data have been split up between MO and KS.

**Revisions to the Historic Point-in-Time Estimates**

On rare occasions, the Point-in-Time estimates published in prior editions of the AHAR have been subsequently updated. The estimates described in this file represent the latest versions of these data (as of the publication of this file). The revisions are summarized below:

1. Beginning in the 2014 AHAR Part 1, the PIT estimates of unsheltered people experiencing homelessness in the Los Angeles City and County CoC, CA-600, were updated for the years 2007–2013. Within the CoC, the adjustments subtracted: 20,746 total people from 2007 and 2008; 9,451 total people in 2009 and 2010; 10,800 total people in 2011 and 2012; and 18,274 total people from 2013. These adjustments also caused drops in the key unsheltered populations reported on the AHAR, individuals, people in families, veterans, and chronically homeless individuals. More details on the size of each adjustment, by population, can be found in the 2014 AHAR Part 1.

2. Beginning in the 2014 AHAR Part 1, the PIT estimate of veterans experiencing homelessness in shelter projects in the Phoenix/Mesa/Maricopa County Regional CoC, AZ-502, was updated for the year 2013, increasing by 214 veterans. This update did not change the total number of people experiencing homelessness in shelter projects (or overall) in the CoC—just the number of those people who were classified as veterans.

3. Beginning in the 2015 AHAR Part 1, the PIT estimates of unsheltered people experiencing homelessness in the Las Vegas/Clark County CoC, NV-500, were updated for the years 2007–2014. Within the CoC, the adjustments subtracted: 3,884 total people from 2007 and 2008; 3,389 total people in 2009 and 2010; 1,429 total people in 2011 and 2012; 1,404 total people from 2013; and 1,974 total people from 2014. These adjustments also caused drops in the key unsheltered populations reported on the AHAR, individuals, people in families, veterans, and chronically homeless individuals. More details on the size of each adjustment, by population, can be found in the 2015 AHAR Part 1.

4. Beginning in the 2015 AHAR Part 1, the PIT estimates of veterans experiencing homelessness in the Anchorage CoC, AK-500, were updated for the year 2014. The sheltered estimate for this CoC increased by 71 veterans, and the unsheltered estimate increased by 18 veterans. Neither of these updates changed the total number of people experiencing homelessness in the CoC—just the number of those people who were classified as veterans.

5. Beginning in the 2017 AHAR Part 2 and the 2018 AHAR Part 1, the PIT estimates of unsheltered people experiencing homelessness in the Los Angeles City and County CoC, CA-600, were updated for the year 2017, decreasing by a total of 2,746 people. The adjustment also caused drops in the key unsheltered populations reported on the AHAR, individuals, people in families, veterans, and chronically homeless individuals. More details on the size of each adjustment, by population, can be found in the 2017 AHAR Part 2 and the 2018 AHAR Part 1.

6. Beginning in the 2019 AHAR Part 1, the PIT estimates describing people experiencing homelessness in 2018 in Danbury, Connecticut, were shifted between two Connecticut CoCs to reflect a change in the jurisdictions they serve; 123 people experiencing homelessness in Danbury and originally reported in CT-505's 2018 PIT count were moved to CT-503. This shift did not change the national estimates or state estimates, as it simply moved people from one Connecticut CoC to another.

7. a MO-604 covers territory in both Missouri and Kansas. The record described in this file represents the CoC's total territory, the sum of the point-in-time estimates the CoC separately reported for the portions of its territory in MO and in KS. However, in the companion file, Point-in-Time Estimates by State, MO-604's data have been split up between MO and KS.


**CoC Mergers**

```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
PIT_CoC_Mergers <- read_excel("Data/2nd_project/2nd project 2015-2020-PIT-Estimates-by-CoC.xlsx", sheet =3)

# kable(PIT_CoC_Mergers[1:110,])

reactable(PIT_CoC_Mergers, searchable = TRUE, showPageSizeOptions = TRUE, defaultPageSize = 10, highlight = TRUE, bordered = TRUE)

```

